### ISSUE TITLE
Would you mind shipping a new version?

### ISSUE THREAD

**Issue by vito** [chmouel/nextmeeting#2]
Hi there, thanks for working on this, it's basically the only thing keeping me from missing all my meetings. :)

There's a fix on `main` that I could really use, since currently my menubar is flashing at incorrect times:

https://github.com/chmouel/nextmeeting/commit/9ee6d231eb346d006849583c48eedd196e31f55d#diff-93e79ac8ef07ce8bc1875658d0c566fc8356983d929d66f6093136df69415c3bR185

I'm currently installing this package through `pip` so would appreciate having a new version available with this fix. :pray:

**Comment by chmouel** [comment]
You are right i should have done that earlier thanks for the reminder,

1.2.2 has just been released!
